"""schema v3 (project credit_limit for debt-risk model)

Revision ID: a036cc892a7e
Revises: 
Create Date: 2026-06-04 05:55:40.106147
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a036cc892a7e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_param',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('industry_norm',
    sa.Column('oked', sa.String(length=8), nullable=False),
    sa.Column('k1_min', sa.Float(), nullable=False),
    sa.Column('k2_min', sa.Float(), nullable=False),
    sa.Column('k3_max', sa.Float(), nullable=False),
    sa.Column('roa_min', sa.Float(), nullable=False),
    sa.Column('autonomy', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('oked')
    )
    op.create_table('raw_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('form_id', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_raw_source_external')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('oked', sa.String(length=8), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporting_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('digital_project_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('pclass', sa.String(length=16), nullable=False),
    sa.Column('npv', sa.Float(), nullable=True),
    sa.Column('rov', sa.Float(), nullable=True),
    sa.Column('var_type', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('efficiency_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('economic_index', sa.Float(), nullable=True),
    sa.Column('ecological_index', sa.Float(), nullable=True),
    sa.Column('social_index', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('efficiency_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('value_before', sa.Float(), nullable=True),
    sa.Column('value_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maturity_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('need_avg', sa.Float(), nullable=False),
    sa.Column('capability_avg', sa.Float(), nullable=False),
    sa.Column('maturity', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_run')
    op.drop_table('maturity_assessment')
    op.drop_table('efficiency_indicator')
    op.drop_table('efficiency_assessment')
    op.drop_table('digital_project_item')
    op.drop_table('user_account')
    op.drop_table('reporting_period')
    op.drop_table('project')
    op.drop_table('organization')
    op.drop_table('region')
    op.drop_table('raw_submission')
    op.drop_table('industry_norm')
    op.drop_table('calibration_param')
    # ### end Alembic commands ###
